### ISSUE TITLE
File Not Found?

### ISSUE THREAD

**Issue by lemkeant** [DerDanilo/proxmox-stuff#11]
Disclaimer, I suck with linux and Proxmox, but Im trying to learn. 

I was interested in this to backup my node and following the readme. I can run the first command to get the script, and run the 2nd command to set the directory. However, when running the chmod command, I'm receiving "chmod: cannot access './prox_config_backup.sh': No such file or directory". It's displaying the script, but doesnt seem to be saving it. 

Is there a command Im missing? The readme seems straightforward, but there's obviously something Im missing as it's not saving the file?

**Comment by DerDanilo** [comment]
Just give it the full path to the script. Most probably you are in the wrong dir if the previous commands worked.
