### ISSUE TITLE
Error message running the script

### ISSUE THREAD

**Issue by jolu1705** [DerDanilo/proxmox-stuff#14]
Hi,

I get the following error running the script:
```
tar: /var/lib/pve-cluster/.: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```
Any idea?

**Comment by jolu1705** [comment]
Creating the directory "/var/lib/pve-cluster" manually makes the script work.
Maybe it should be checked if the directory is there or not.
If proxmox is not using a cluster that directory seems not to be there by default (because its not needed).

The script should check if it is there or not and go on even if it does not exist.

**Comment by DerDanilo** [comment]
Please open a PR for your suggestion as I lack the time to implement this at the moment.

**Comment by phidauex** [comment]
Hi, I just checked on my default Proxmox 7 install, and it does create and populate the /var/lib/pve-cluster/ folder even though I'm not using, and have never configured a cluster.

**Comment by DerDanilo** [comment]
Since noone opens a PR for that I'll try to fix this soon as well. I checked on reference (single node) systems and the `pve-cluster` folder is not populated on all of them. Hence we should add a check for this folder I guess.

**Comment by DerDanilo** [comment]
I am sorry guys. I forgot about this. Unfortunately I have absolutely no time for site projects at the moment. PRs are welcome.

**Comment by Yonny24** [comment]
> Hi,
> 
> I get the following error running the script:
> 
> ```
> tar: /var/lib/pve-cluster/.: Cannot stat: No such file or directory
> tar: Exiting with failure status due to previous errors
> ```
> 
> Any idea?

Similar error here. After running the first script all looks ok.

 Sorry how did you fix the issue?

But when I try to mod the permissions I get this error.

`compressandarchive

root@pve2:~# chmod +x ./prox_config_backup.sh
chmod: cannot access './prox_config_backup.sh': No such file or directory`

**Comment by DerDanilo** [comment]
The error appears when the system is a single node without a cluster. This doesn't seem a permission issue to me but the absents of the 'pve-cluster' dir itself.

I suggest that someone improves the script to actually check if the node runs in a cluster or not.
