### ISSUE TITLE
Info on backup step large or minor step ?

### ISSUE THREAD

**Issue by docop** [DerDanilo/proxmox-stuff#20]
Hi  Thanks for your script, it look quite interesting and what i was looking for to properly understand. Actually, is the whole proxmox is only into these 3 folders that are being restore/backup :  /etc  /var  /root  ?
 Mean, i install a fresh proxmox iso and simply put back the 3 folder and it's all get to where i was ?  Or the backup is more just for small change made..?

 minus the vm that need to be re-import of course..
Thanks

**Comment by DerDanilo** [comment]
It's not that simple. Please ask such question in the Proxmox forum. Github is the wrong place for that. If you find anything missing from the backup you are welcome to open an issue. Thanks!
