### ISSUE TITLE
Add cron.hourly/daily/weekly instruction note to readme!

### ISSUE THREAD

**Issue by peterge1998** [DerDanilo/proxmox-stuff#25]
https://blog.peterge.de/proxmox-host-clone/

Was able to do it by following these steps:
```
Copy it into /etc/cron.weekly
chmod 755 the script
rename it to prox_config_backup
test with run-parts -v --test /etc/cron.weekly if it contains errors
```

I think its more simple to automate a backup task. Plus if you enable mail notifications, it will notify the user with the outpout the script writes!

**Comment by DerDanilo** [comment]
@peterge1998 Can you please submit a PR? Then others can also make use of this.
Thanks

**Comment by peterge1998** [comment]
> @peterge1998 Can you please submit a PR? Then others can also make use of this. Thanks

See #31 :)
