### ISSUE TITLE
Status Information at beginning of output

### ISSUE THREAD

**Issue by thn80** [DerDanilo/proxmox-stuff#28]
Hi,

I am running the backup script as Cron job and receive an automatically generated E-Mail everytime.
Would it be possible to modify the script, that it prints the status of the backup in the very first line of the E-Mail, so that it is easier to check the overall backup result? I think the script should buffer all output into a temporary variable and at the end output the status first and then print the buffered content.

Thanks,

Thomas

**Comment by DerDanilo** [comment]
Hi Thomas.

I like the idea but have not time to implement this. You're welcome to commit a PR that implements this. I am sure that here are some people that might welcome this.

Thanks
