### ISSUE TITLE
/etc/pve is completely empty

### ISSUE THREAD

**Issue by homonto** [DerDanilo/proxmox-stuff#32]
I run your script and I am not getting the point: the folder /etc/pve is completely empty in the file:
proxmoxetc.2023-03-10.19.30.04.tar

I followed your wiki and while all other folders are ok, this one - quite important I believe - is empty
what am I doing wrong?

<img width="1407" alt="Screenshot 2023-03-10 at 19 43 19" src="https://user-images.githubusercontent.com/46562447/224412952-03b24e30-bb8f-4a93-a620-0ade9732d565.png">
<img width="1344" alt="Screenshot 2023-03-10 at 19 41 28" src="https://user-images.githubusercontent.com/46562447/224412954-8979088b-9bfb-4658-88f6-4086cf46ad87.png">

**Comment by homonto** [comment]
but when I enter the below commands manually:
```
cd /
tar cfz etc.tar.gz etc
```

I get the file with everything from etc, including /etc/pve as well

**Comment by DerDanilo** [comment]
I don't use the script anymore since we implemented PBS based backup of the PVE cluster config. Still waiting for the proxmox team to actually integrate PBS backup for PVE cluster config/database as they announced.

Did you run the script with proper permission? `/etc/pve` is only accessible with root.

**Comment by homonto** [comment]
of course as root

**Comment by LarsNorgaard** [comment]
Same problem here. Also no symlinks for the files in pve.

`lrwxr-xr-x 1 root www-data    0 Jan  1  1970 qemu-server -> nodes/atlas/qemu-server`
`lrwxr-xr-x 1 root www-data    0 Jan  1  1970 openvz -> nodes/atlas/openvz`
`lrwxr-xr-x 1 root www-data    0 Jan  1  1970 lxc -> nodes/atlas/lxc`
`lrwxr-xr-x 1 root www-data    0 Jan  1  1970 local -> nodes/atlas`

nodes folder is missing.

**Comment by homonto** [comment]
@DerDanilo  said he is not maintaining this anymore ;-)
but to be honest he should remove it from github or announce that it is broken for the current PVE version - some people could rely on it and then... you know - shit happens ;)

**Comment by fma965** [comment]
remove 
--one-file-system from
https://github.com/DerDanilo/proxmox-stuff/blob/master/prox_config_backup.sh#L128
and
https://github.com/DerDanilo/proxmox-stuff/blob/master/prox_config_backup.sh#L130

not sure L130 is needed but L128 for sure

‘--one-file-system’
Prevents tar from crossing file system boundaries when archiving. Use in conjunction with any write operation.

Proxmox uses cluster file system for /etc/pve

**Comment by gfn256** [comment]
@Fma965 Excellent! I wonder if this script ever worked (without your amendments) to copy /etc/pve. Would seem an oversight by the original @DerDanilo . I wonder why he added  `--one-file-system` at all. He must have had a good reason, I imagine.

Have never restored (yet!).  Would like to try someday - to see if it really works!

**Comment by DerDanilo** [comment]
The script worked at some point. And yes, it actually copied the files in /etc/pve. It was intended to backup single node setups. If I remember correctly (and I may be wrong) single node systems don't have a mounted filesystem at /etc/pve.

**Comment by fma965** [comment]
This is correct although it's still odd that that parameter was added, especially if you never used a cluster 🤔

**Comment by DerDanilo** [comment]
I don't even remember the time I wrote the script. I must have had a reason for it. :)

**Comment by fma965** [comment]
> I don't even remember the time I wrote the script. I must have had a reason for it. :)

Haha, I know that feeling! 😉

**Comment by gfn256** [comment]
> I don't even remember the time I wrote the script. I must have had a reason for it. :)

Happens to me all the time - if there is a time-gap when relooking at any script!
Anyway thanks again.
