### ISSUE TITLE
Hint: script restores /etc/fstab - not good on new setups

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [DerDanilo/proxmox-stuff#33]
Hi,
thanks for this little helper! I used it to restore/build a new single node setup.

One thing to keep in mind:
the script would also restore ```/etc/fstab```, which in case of a new setup would contain different mounts with different ```UUIDs```. So it is  required to exclude ```/etc/fstab``` from the restore process, otherwise your fresh install might not boot after the restore.

**Comment by HernandoR** [comment]
that's also what I'm worried about. Are there any other files similar to `/etc/fstab` that require notice?

**Comment by DerDanilo** [comment]
I intended the script for desaster recovery which usually includes manual verification of configuration. Your suggestion is valid though. 
Maybe someone can add a tweak to comment out all lines in the /etc/fstab backup file. The script should throw a warning about that though.
