### ISSUE TITLE
How to stop email alert when running from chron

### ISSUE THREAD

**Issue by CV8R** [DerDanilo/proxmox-stuff#42]
I have added the script to cron and it works great.  But each time it runs a receive an email alert.

`Cron <root@pve1> test -x /usr/sbin/anacron || { cd / && run-parts --report /etc/cron.daily; }`

Is there a way to stop it outputting and sending the email.  Ideally, only send if it fails.

**Comment by DerDanilo** [comment]
pipe into the void.

https://www.cyberciti.biz/faq/how-to-redirect-output-and-errors-to-devnull/

**Comment by CV8R** [comment]
Is there a better way that ignores if the backup is successful and sends the email if it fails?
