### ISSUE TITLE
add support for proxmox backup server ?

### ISSUE THREAD

**Issue by corwinou** [DerDanilo/proxmox-stuff#43]
Nice tool, thanks for sharing ! exactly what I was looking for my PVE cluster. It would even better if you can support PBS, with only a few minor changes (eg. /etc/pve to be replaced)

**Comment by DerDanilo** [comment]
PBS Support is already provided more or less. There is a pbs client backup ansible role that can be configured to backup pve nodes config.

https://github.com/DerDanilo/proxmox-stuff/tree/master/Ansible/pbs_client_backups
