### ISSUE TITLE
Try to run the script but get the error

### ISSUE THREAD

**Issue by danfmihai** [DerDanilo/proxmox-stuff#7]
First try to run the script and get this error: 
`prox_config_backup.sh: 25: prox_config_backup.sh: function: not found`

**Comment by danfmihai** [comment]
Fixed it by removing the word function (used the script on Ubuntu 18)

**Comment by DerDanilo** [comment]
Please commit any fixes to others can also profit from it. Thanks!

**Comment by DerDanilo** [comment]
@danfmihai Do you have info about the exact changes you did to make this work?
Also, why do you run the script unter Ubuntu 18? It is supposed to run on the PVE nodes which are based on Debian (using a customized ubuntu kernel).
